import {
  LayoutDashboard,
  Map,
  Route,
  Warehouse,
  Users,
  Package,
  Boxes,
  Wallet,
  Building2,
  Receipt,
  MapPinned,
  ChartSpline,
  Bell,
  Plane,
  Ship,
  TrainFront,
  Truck,
  Home,
  ShieldCheck,
  History,
  FileSignature,
  CreditCard,
  UserCircle,
  PackagePlus,
} from 'lucide-react'

export const operatorNav = [
  { label: 'Dashboard', path: '/app/dashboard', icon: LayoutDashboard },
  { label: 'Map', path: '/app/map', icon: Map },
  { label: 'Trips', path: '/app/trips', icon: Route },
  {
    label: 'Warehouse',
    icon: Boxes,
    children: [
      { label: 'Overview', path: '/app/warehouse' },
      { label: 'Labelling & Batching', path: '/app/warehouse/labelling' },
      { label: 'Smart Assignment', path: '/app/warehouse/assignment' },
      { label: 'Geofences & Zones', path: '/app/warehouse/zones' },
      { label: 'Dispatch & Tracking', path: '/app/warehouse/dispatch' },
      { label: 'Route Optimisation', path: '/app/warehouse/routes' },
      { label: 'Driver Board', path: '/app/warehouse/drivers' },
    ],
  },
  {
    label: 'Assets',
    icon: Warehouse,
    children: [
      { label: 'Overview', path: '/app/assets' },
      { section: 'Ground' },
      { label: 'Yards & Depots', path: '/app/assets/yards' },
      { label: 'Vehicles', path: '/app/assets/vehicles' },
      { label: 'Trailers', path: '/app/assets/trailers' },
      { label: 'Equipment', path: '/app/assets/equipment' },
      { label: 'Check In / Out', path: '/app/assets/check-in' },
      { label: 'Rail', path: '/app/assets/rail' },
      { section: 'Maritime' },
      { label: 'Maritime', path: '/app/assets/maritime' },
      { section: 'Air' },
      { label: 'Airports', path: '/app/assets/air/airports' },
      { label: 'Aeroplanes', path: '/app/assets/air/aeroplanes' },
      { label: 'Air Equipment', path: '/app/assets/air/equipment' },
      { label: 'Crew', path: '/app/assets/air/crew' },
    ],
  },
  { label: 'Drivers', path: '/app/drivers', icon: Users },
  {
    label: 'Orders',
    icon: Package,
    children: [
      { label: 'All Orders', path: '/app/orders' },
      { label: 'Pending', path: '/app/orders/pending' },
      { label: 'History', path: '/app/orders/history' },
      { label: 'Invoices', path: '/app/orders/invoices' },
    ],
  },
  { label: 'Wallet', path: '/app/wallet', icon: Wallet },
  { label: 'Customers', path: '/app/customers', icon: Building2 },
  {
    label: 'Expenses',
    icon: Receipt,
    children: [
      { label: 'Fuel Logs', path: '/app/expenses/fuel' },
      { label: 'Yard Fees', path: '/app/expenses/yard-fees' },
      { label: 'Airport Fees', path: '/app/expenses/airport-fees' },
      { label: 'Salaries', path: '/app/expenses/salaries' },
    ],
  },
  { label: 'Geomapping', path: '/app/geomapping', icon: MapPinned },
  { label: 'Geo Analytics', path: '/app/geo-analytics', icon: ChartSpline },
  { label: 'Notifications', path: '/app/notifications', icon: Bell },
]

export const customerNav = [
  { label: 'Overview', path: '/customer/overview', icon: LayoutDashboard },
  { label: 'Deliveries', path: '/customer/deliveries', icon: Truck },
  { label: 'New Booking', path: '/customer/new-booking', icon: PackagePlus },
  { label: 'Parcel Tracking', path: '/customer/tracking', icon: Package },
  { label: 'Documents (KYC/FICA/AML)', path: '/customer/documents', icon: ShieldCheck },
  { label: 'Booking History', path: '/customer/bookings', icon: History },
  { label: 'Invoices', path: '/customer/invoices', icon: Receipt },
  { label: 'Contracts', path: '/customer/contracts', icon: FileSignature },
  { label: 'Payments', path: '/customer/payments', icon: CreditCard },
  { label: 'Notifications', path: '/customer/notifications', icon: Bell },
  { label: 'Account', path: '/customer/account', icon: UserCircle },
]

export const modeChips = [
  { label: 'Road', icon: Truck },
  { label: 'Rail', icon: TrainFront },
  { label: 'Maritime', icon: Ship },
  { label: 'Air', icon: Plane },
]

export const publicLinks = [
  { label: 'Home', path: '/', icon: Home },
  { label: 'Login', path: '/login' },
]
